#!/bin/bash

# downtogit 0.1
# Actualiza facilmente tu repositorio local.

# Modo de uso: copia o mueve este script a /usr/bin o /usr/local/bin y desde el directorio donde se encuentre la copia de un repo git, ejecútalo de esta manera:
# downtogit

# Comprobamos si el directorio en el que estamos es de un repositorio git
if [ ! -d '.git' ]; then
	echo 'Esta carpeta no contiene un repositorio Git'
	exit -1
fi

# Ahora comprobamos si se le paso algun parametro
if [ $# == 0 ]; then
	
	echo "Descargando las modificaciones de GIT a tu repositorio local"
	git pull
	echo "downtogit: tu repositorio local ha sido actualizado"
else
	echo "downtogit: ¡Error! este script no necesita ningún parámetro"
	exit -1

fi
